
-- Gallery
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/9P3A5963.JPG', 'Albatross Baja Vehicle Field Test', 'Testing & Track', 0);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/9P3A7208.JPG', 'High-Chroma Endurance Rally', 'Testing & Track', 1);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/DSC09637.JPG', 'Chassis Precision & TIG Welds', 'Chassis & Frame', 2);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/DSCN0816.JPG', 'Steering & Ergonomic Controls', 'Telemetry & Cockpit', 3);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/DSC00220.jpg', 'All-Terrain Offroad Prototype', 'Testing & Track', 4);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/DSC_5688.jpeg', 'Dynamic Double-A Arm Suspension', 'Suspension & Wheels', 5);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG-20250812-WA0006.jpg', 'Night Pit Scrutineering & Check', 'Telemetry & Cockpit', 6);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG20260111194040.jpg', 'High-Speed Sand Dune Sprint', 'Testing & Track', 7);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_0292.jpg', 'Custom Tuned CVT Powertrain', 'Powertrain', 8);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_0497.JPG', 'Endurance Championship Vehicle', 'Chassis & Frame', 9);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_20240816_090641.jpg', 'Air Dam & Shock Telemetry', 'Suspension & Wheels', 10);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_5855.JPG', 'All-Terrain Mud & Obstacle Run', 'Testing & Track', 11);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_5888.JPG', 'Cockpit Dashboard & Brake Bias', 'Telemetry & Cockpit', 12);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_6603.JPG', 'High-G Cornering Dynamics', 'Testing & Track', 13);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_6840.jpg', 'Chassis Tubing Structural Audit', 'Chassis & Frame', 14);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/IMG_9384.JPG', 'All-Terrain Offroad Wheel Assembly', 'Suspension & Wheels', 15);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/TRB_2.JPG', 'Team Red Baron Motorsport Prototype', 'Chassis & Frame', 16);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/WBD09944.JPG', 'Sensor Calibration & Telemetry', 'Telemetry & Cockpit', 17);
INSERT INTO gallery_images (image_url, title, category, sort_order) VALUES ('https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/gallery/20230405_171839.jpg', 'BAJA National Championship Sprint', 'Testing & Track', 18);

-- Team Members
DO $$
DECLARE ty_id uuid;
BEGIN
  INSERT INTO team_years (year_label, sort_order) VALUES ('2025-26', 0) RETURNING id INTO ty_id;
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Captain', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 0);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'CFO & COO', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 1);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Mechanical CTO', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 2);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Electrical CTO', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 3);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Suspension Lead', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 4);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Brakes & Steering Lead', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 5);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Vehicle Dynamics Member', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 6);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Jr. Vehicle Dynamics Member', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 7);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'High Voltage Lead', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 8);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Low Voltage Lead', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 9);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'B-Plan Lead & High Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 10);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 11);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 12);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 13);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Jr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 14);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Jr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 15);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Jr. Low Voltage Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 16);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Chassis Lead', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 17);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Aerodynamics Lead', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 18);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Structures Member', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 19);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Structures Member', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 20);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Structures Member', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 21);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Drivetrain Lead', 'Drivetrain', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 22);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Drivetrain Member', 'Drivetrain', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 23);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Jr. Drivetrain Member', 'Drivetrain', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 24);
  INSERT INTO team_years (year_label, sort_order) VALUES ('2024-25', 1) RETURNING id INTO ty_id;
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Vice Captain & Dynamics Lead', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 0);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Treasury & Finance Head', 'Management', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 1);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Sr. Suspension Engineer', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 2);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Telemetry & DAQ Lead', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 3);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'FEA & Chassis Engineer', 'Structures', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 4);
  INSERT INTO team_years (year_label, sort_order) VALUES ('2023-24', 2) RETURNING id INTO ty_id;
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Junior Vehicle Engineer', 'Vehicle Dynamics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 0);
  INSERT INTO team_members (team_year_id, name, role, department, image_url, linkedin_url, sort_order) VALUES (ty_id, 'Untitled', 'Wiring & Harness Member', 'Electronics', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/team_person.png', 'https://linkedin.com', 1);
END $$;

-- Sponsors
DO $$
DECLARE st_id uuid;
BEGIN
  INSERT INTO sponsor_tiers (tier_name, sort_order) VALUES ('TITLE SPONSORS', 0) RETURNING id INTO st_id;
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'ALTIUM', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/ALTIUM.png', 'https://www.altium.com', 0);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'GEFRAN', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/GEFRAN.png', 'https://www.gefran.com', 1);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'MAHLE', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/MAHLE.png', 'https://www.mahle.com', 2);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'STAR ENGINEERS', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/STAR ENGINEERS.png', 'https://www.starengineers.com', 3);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'TRIVIKARAM', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/TRIVIKARAM.png', '#', 4);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'VARROC', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/VARROC.png', 'https://varroc.com', 5);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'ROSENBERGER', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/TITLE/rosenberger.png', 'https://www.rosenberger.com', 6);
  INSERT INTO sponsor_tiers (tier_name, sort_order) VALUES ('PLATINUM SPONSORS', 1) RETURNING id INTO st_id;
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'SKF', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/SKF.png', 'https://www.skf.com', 0);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'FLUKE', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/FLUKE.png', 'https://www.fluke.com', 1);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'CASTAL DIES', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/CASTAL DIES.png', '#', 2);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'ESBEE', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/ESBEE.png', 'https://esbee-electrotech.com', 3);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'ANUCOOL', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/ANUCOOL.png', '#', 4);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'C2M', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/PLATINUM/C2M.png', '#', 5);
  INSERT INTO sponsor_tiers (tier_name, sort_order) VALUES ('GOLD SPONSORS', 2) RETURNING id INTO st_id;
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'MITUTOYO', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/MITUTOYO.png', 'https://www.mitutoyo.co.jp/global/', 0);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'BALAJI WIRES', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/BALAJI WIRES.png', '#', 1);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'COMPOSITE TOMORROW', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/COMPOSITE TOMORROW.png', '#', 2);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'BHARAT MECHATRONICS', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/BHARAT MECHATRONICS.png', '#', 3);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'ELECTRO CATALYST', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/ELECTRO CATALYST.png', '#', 4);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'VR COATING', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/GOLD/VR COATING.png', '#', 5);
  INSERT INTO sponsor_tiers (tier_name, sort_order) VALUES ('SILVER SPONSORS', 3) RETURNING id INTO st_id;
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'MOLEX', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/MOLEX.png', 'https://www.molex.com', 0);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'BEICO', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/BEICO.png', '#', 1);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'METADEK', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/METADEK.png', '#', 2);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'SHOGINI', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/SHOGINI.png', '#', 3);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'SHITAL PLASMA', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/SHITAL PLASMA.png', '#', 4);
  INSERT INTO sponsors (tier_id, name, logo_url, website_url, sort_order) VALUES (st_id, 'CHINTAMANI', 'https://axzwucvnrjtenvvrxfew.supabase.co/storage/v1/object/public/trb-media/sponsors/SILVER/CHINTAMANI.png', '#', 5);
END $$;
